package weixin.assistant.model;

public class KeyValue {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column key_value.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column key_value.key_str
     *
     * @mbggenerated
     */
    private String keyStr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column key_value.value_str
     *
     * @mbggenerated
     */
    private String valueStr;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key_value
     *
     * @mbggenerated
     */
    public KeyValue(Integer id, String keyStr, String valueStr) {
        this.id = id;
        this.keyStr = keyStr;
        this.valueStr = valueStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table key_value
     *
     * @mbggenerated
     */
    public KeyValue() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column key_value.id
     *
     * @return the value of key_value.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column key_value.id
     *
     * @param id the value for key_value.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column key_value.key_str
     *
     * @return the value of key_value.key_str
     *
     * @mbggenerated
     */
    public String getKeyStr() {
        return keyStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column key_value.key_str
     *
     * @param keyStr the value for key_value.key_str
     *
     * @mbggenerated
     */
    public void setKeyStr(String keyStr) {
        this.keyStr = keyStr == null ? null : keyStr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column key_value.value_str
     *
     * @return the value of key_value.value_str
     *
     * @mbggenerated
     */
    public String getValueStr() {
        return valueStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column key_value.value_str
     *
     * @param valueStr the value for key_value.value_str
     *
     * @mbggenerated
     */
    public void setValueStr(String valueStr) {
        this.valueStr = valueStr == null ? null : valueStr.trim();
    }
}