package weixin.assistant.model;

import java.util.Date;

public class VipPayOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_pay_order.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_pay_order.member_id
     *
     * @mbggenerated
     */
    private Integer memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_pay_order.business_id
     *
     * @mbggenerated
     */
    private Integer businessId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_pay_order.out_trade_no
     *
     * @mbggenerated
     */
    private String outTradeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_pay_order.pay_type
     *
     * @mbggenerated
     */
    private Integer payType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_pay_order.fee
     *
     * @mbggenerated
     */
    private Integer fee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_pay_order.coupons_type
     *
     * @mbggenerated
     */
    private Integer couponsType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_pay_order.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_pay_order.finish_time
     *
     * @mbggenerated
     */
    private Date finishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_pay_order.status
     *
     * @mbggenerated
     */
    private Short status;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_pay_order
     *
     * @mbggenerated
     */
    public VipPayOrder(Integer id, Integer memberId, Integer businessId, String outTradeNo, Integer payType, Integer fee, Integer couponsType, Date createTime, Date finishTime, Short status) {
        this.id = id;
        this.memberId = memberId;
        this.businessId = businessId;
        this.outTradeNo = outTradeNo;
        this.payType = payType;
        this.fee = fee;
        this.couponsType = couponsType;
        this.createTime = createTime;
        this.finishTime = finishTime;
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_pay_order
     *
     * @mbggenerated
     */
    public VipPayOrder() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_pay_order.id
     *
     * @return the value of vip_pay_order.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_pay_order.id
     *
     * @param id the value for vip_pay_order.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_pay_order.member_id
     *
     * @return the value of vip_pay_order.member_id
     *
     * @mbggenerated
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_pay_order.member_id
     *
     * @param memberId the value for vip_pay_order.member_id
     *
     * @mbggenerated
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_pay_order.business_id
     *
     * @return the value of vip_pay_order.business_id
     *
     * @mbggenerated
     */
    public Integer getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_pay_order.business_id
     *
     * @param businessId the value for vip_pay_order.business_id
     *
     * @mbggenerated
     */
    public void setBusinessId(Integer businessId) {
        this.businessId = businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_pay_order.out_trade_no
     *
     * @return the value of vip_pay_order.out_trade_no
     *
     * @mbggenerated
     */
    public String getOutTradeNo() {
        return outTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_pay_order.out_trade_no
     *
     * @param outTradeNo the value for vip_pay_order.out_trade_no
     *
     * @mbggenerated
     */
    public void setOutTradeNo(String outTradeNo) {
        this.outTradeNo = outTradeNo == null ? null : outTradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_pay_order.pay_type
     *
     * @return the value of vip_pay_order.pay_type
     *
     * @mbggenerated
     */
    public Integer getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_pay_order.pay_type
     *
     * @param payType the value for vip_pay_order.pay_type
     *
     * @mbggenerated
     */
    public void setPayType(Integer payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_pay_order.fee
     *
     * @return the value of vip_pay_order.fee
     *
     * @mbggenerated
     */
    public Integer getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_pay_order.fee
     *
     * @param fee the value for vip_pay_order.fee
     *
     * @mbggenerated
     */
    public void setFee(Integer fee) {
        this.fee = fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_pay_order.coupons_type
     *
     * @return the value of vip_pay_order.coupons_type
     *
     * @mbggenerated
     */
    public Integer getCouponsType() {
        return couponsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_pay_order.coupons_type
     *
     * @param couponsType the value for vip_pay_order.coupons_type
     *
     * @mbggenerated
     */
    public void setCouponsType(Integer couponsType) {
        this.couponsType = couponsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_pay_order.create_time
     *
     * @return the value of vip_pay_order.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_pay_order.create_time
     *
     * @param createTime the value for vip_pay_order.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_pay_order.finish_time
     *
     * @return the value of vip_pay_order.finish_time
     *
     * @mbggenerated
     */
    public Date getFinishTime() {
        return finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_pay_order.finish_time
     *
     * @param finishTime the value for vip_pay_order.finish_time
     *
     * @mbggenerated
     */
    public void setFinishTime(Date finishTime) {
        this.finishTime = finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_pay_order.status
     *
     * @return the value of vip_pay_order.status
     *
     * @mbggenerated
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_pay_order.status
     *
     * @param status the value for vip_pay_order.status
     *
     * @mbggenerated
     */
    public void setStatus(Short status) {
        this.status = status;
    }
}