package weixin.assistant.model;

import java.util.Date;

public class WeixinUserAuthorizer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_user_authorizer.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_user_authorizer.weixin_user_id
     *
     * @mbggenerated
     */
    private Integer weixinUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_user_authorizer.open_id
     *
     * @mbggenerated
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_user_authorizer.union_id
     *
     * @mbggenerated
     */
    private String unionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_user_authorizer.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_user_authorizer.scope
     *
     * @mbggenerated
     */
    private String scope;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_user_authorizer.access_token
     *
     * @mbggenerated
     */
    private String accessToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_user_authorizer.token_expire_time
     *
     * @mbggenerated
     */
    private Date tokenExpireTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_user_authorizer.refresh_token
     *
     * @mbggenerated
     */
    private String refreshToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_user_authorizer.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_user_authorizer
     *
     * @mbggenerated
     */
    public WeixinUserAuthorizer(Integer id, Integer weixinUserId, String openId, String unionId, String code, String scope, String accessToken, Date tokenExpireTime, String refreshToken, Integer status) {
        this.id = id;
        this.weixinUserId = weixinUserId;
        this.openId = openId;
        this.unionId = unionId;
        this.code = code;
        this.scope = scope;
        this.accessToken = accessToken;
        this.tokenExpireTime = tokenExpireTime;
        this.refreshToken = refreshToken;
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_user_authorizer
     *
     * @mbggenerated
     */
    public WeixinUserAuthorizer() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_user_authorizer.id
     *
     * @return the value of weixin_user_authorizer.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_user_authorizer.id
     *
     * @param id the value for weixin_user_authorizer.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_user_authorizer.weixin_user_id
     *
     * @return the value of weixin_user_authorizer.weixin_user_id
     *
     * @mbggenerated
     */
    public Integer getWeixinUserId() {
        return weixinUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_user_authorizer.weixin_user_id
     *
     * @param weixinUserId the value for weixin_user_authorizer.weixin_user_id
     *
     * @mbggenerated
     */
    public void setWeixinUserId(Integer weixinUserId) {
        this.weixinUserId = weixinUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_user_authorizer.open_id
     *
     * @return the value of weixin_user_authorizer.open_id
     *
     * @mbggenerated
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_user_authorizer.open_id
     *
     * @param openId the value for weixin_user_authorizer.open_id
     *
     * @mbggenerated
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_user_authorizer.union_id
     *
     * @return the value of weixin_user_authorizer.union_id
     *
     * @mbggenerated
     */
    public String getUnionId() {
        return unionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_user_authorizer.union_id
     *
     * @param unionId the value for weixin_user_authorizer.union_id
     *
     * @mbggenerated
     */
    public void setUnionId(String unionId) {
        this.unionId = unionId == null ? null : unionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_user_authorizer.code
     *
     * @return the value of weixin_user_authorizer.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_user_authorizer.code
     *
     * @param code the value for weixin_user_authorizer.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_user_authorizer.scope
     *
     * @return the value of weixin_user_authorizer.scope
     *
     * @mbggenerated
     */
    public String getScope() {
        return scope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_user_authorizer.scope
     *
     * @param scope the value for weixin_user_authorizer.scope
     *
     * @mbggenerated
     */
    public void setScope(String scope) {
        this.scope = scope == null ? null : scope.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_user_authorizer.access_token
     *
     * @return the value of weixin_user_authorizer.access_token
     *
     * @mbggenerated
     */
    public String getAccessToken() {
        return accessToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_user_authorizer.access_token
     *
     * @param accessToken the value for weixin_user_authorizer.access_token
     *
     * @mbggenerated
     */
    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken == null ? null : accessToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_user_authorizer.token_expire_time
     *
     * @return the value of weixin_user_authorizer.token_expire_time
     *
     * @mbggenerated
     */
    public Date getTokenExpireTime() {
        return tokenExpireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_user_authorizer.token_expire_time
     *
     * @param tokenExpireTime the value for weixin_user_authorizer.token_expire_time
     *
     * @mbggenerated
     */
    public void setTokenExpireTime(Date tokenExpireTime) {
        this.tokenExpireTime = tokenExpireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_user_authorizer.refresh_token
     *
     * @return the value of weixin_user_authorizer.refresh_token
     *
     * @mbggenerated
     */
    public String getRefreshToken() {
        return refreshToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_user_authorizer.refresh_token
     *
     * @param refreshToken the value for weixin_user_authorizer.refresh_token
     *
     * @mbggenerated
     */
    public void setRefreshToken(String refreshToken) {
        this.refreshToken = refreshToken == null ? null : refreshToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_user_authorizer.status
     *
     * @return the value of weixin_user_authorizer.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_user_authorizer.status
     *
     * @param status the value for weixin_user_authorizer.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}