package weixin.assistant.model;

public class WeixinGzhPay {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_gzh_pay.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_gzh_pay.weixin_gzh_id
     *
     * @mbggenerated
     */
    private Integer weixinGzhId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_gzh_pay.mch_id
     *
     * @mbggenerated
     */
    private String mchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_gzh_pay.mch_key
     *
     * @mbggenerated
     */
    private String mchKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_gzh_pay.notify_url
     *
     * @mbggenerated
     */
    private String notifyUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_gzh_pay.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_gzh_pay
     *
     * @mbggenerated
     */
    public WeixinGzhPay(Integer id, Integer weixinGzhId, String mchId, String mchKey, String notifyUrl, Integer status) {
        this.id = id;
        this.weixinGzhId = weixinGzhId;
        this.mchId = mchId;
        this.mchKey = mchKey;
        this.notifyUrl = notifyUrl;
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_gzh_pay
     *
     * @mbggenerated
     */
    public WeixinGzhPay() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_gzh_pay.id
     *
     * @return the value of weixin_gzh_pay.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_gzh_pay.id
     *
     * @param id the value for weixin_gzh_pay.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_gzh_pay.weixin_gzh_id
     *
     * @return the value of weixin_gzh_pay.weixin_gzh_id
     *
     * @mbggenerated
     */
    public Integer getWeixinGzhId() {
        return weixinGzhId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_gzh_pay.weixin_gzh_id
     *
     * @param weixinGzhId the value for weixin_gzh_pay.weixin_gzh_id
     *
     * @mbggenerated
     */
    public void setWeixinGzhId(Integer weixinGzhId) {
        this.weixinGzhId = weixinGzhId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_gzh_pay.mch_id
     *
     * @return the value of weixin_gzh_pay.mch_id
     *
     * @mbggenerated
     */
    public String getMchId() {
        return mchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_gzh_pay.mch_id
     *
     * @param mchId the value for weixin_gzh_pay.mch_id
     *
     * @mbggenerated
     */
    public void setMchId(String mchId) {
        this.mchId = mchId == null ? null : mchId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_gzh_pay.mch_key
     *
     * @return the value of weixin_gzh_pay.mch_key
     *
     * @mbggenerated
     */
    public String getMchKey() {
        return mchKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_gzh_pay.mch_key
     *
     * @param mchKey the value for weixin_gzh_pay.mch_key
     *
     * @mbggenerated
     */
    public void setMchKey(String mchKey) {
        this.mchKey = mchKey == null ? null : mchKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_gzh_pay.notify_url
     *
     * @return the value of weixin_gzh_pay.notify_url
     *
     * @mbggenerated
     */
    public String getNotifyUrl() {
        return notifyUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_gzh_pay.notify_url
     *
     * @param notifyUrl the value for weixin_gzh_pay.notify_url
     *
     * @mbggenerated
     */
    public void setNotifyUrl(String notifyUrl) {
        this.notifyUrl = notifyUrl == null ? null : notifyUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_gzh_pay.status
     *
     * @return the value of weixin_gzh_pay.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_gzh_pay.status
     *
     * @param status the value for weixin_gzh_pay.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}