package weixin.assistant.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class WeixinGzhAuthorizerExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table weixin_gzh_authorizer
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table weixin_gzh_authorizer
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table weixin_gzh_authorizer
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_gzh_authorizer
     *
     * @mbggenerated
     */
    public WeixinGzhAuthorizerExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_gzh_authorizer
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_gzh_authorizer
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_gzh_authorizer
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_gzh_authorizer
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_gzh_authorizer
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_gzh_authorizer
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_gzh_authorizer
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_gzh_authorizer
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_gzh_authorizer
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_gzh_authorizer
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table weixin_gzh_authorizer
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andWeixinGzhIdIsNull() {
            addCriterion("weixin_gzh_id is null");
            return (Criteria) this;
        }

        public Criteria andWeixinGzhIdIsNotNull() {
            addCriterion("weixin_gzh_id is not null");
            return (Criteria) this;
        }

        public Criteria andWeixinGzhIdEqualTo(Integer value) {
            addCriterion("weixin_gzh_id =", value, "weixinGzhId");
            return (Criteria) this;
        }

        public Criteria andWeixinGzhIdNotEqualTo(Integer value) {
            addCriterion("weixin_gzh_id <>", value, "weixinGzhId");
            return (Criteria) this;
        }

        public Criteria andWeixinGzhIdGreaterThan(Integer value) {
            addCriterion("weixin_gzh_id >", value, "weixinGzhId");
            return (Criteria) this;
        }

        public Criteria andWeixinGzhIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("weixin_gzh_id >=", value, "weixinGzhId");
            return (Criteria) this;
        }

        public Criteria andWeixinGzhIdLessThan(Integer value) {
            addCriterion("weixin_gzh_id <", value, "weixinGzhId");
            return (Criteria) this;
        }

        public Criteria andWeixinGzhIdLessThanOrEqualTo(Integer value) {
            addCriterion("weixin_gzh_id <=", value, "weixinGzhId");
            return (Criteria) this;
        }

        public Criteria andWeixinGzhIdIn(List<Integer> values) {
            addCriterion("weixin_gzh_id in", values, "weixinGzhId");
            return (Criteria) this;
        }

        public Criteria andWeixinGzhIdNotIn(List<Integer> values) {
            addCriterion("weixin_gzh_id not in", values, "weixinGzhId");
            return (Criteria) this;
        }

        public Criteria andWeixinGzhIdBetween(Integer value1, Integer value2) {
            addCriterion("weixin_gzh_id between", value1, value2, "weixinGzhId");
            return (Criteria) this;
        }

        public Criteria andWeixinGzhIdNotBetween(Integer value1, Integer value2) {
            addCriterion("weixin_gzh_id not between", value1, value2, "weixinGzhId");
            return (Criteria) this;
        }

        public Criteria andAppIdIsNull() {
            addCriterion("app_id is null");
            return (Criteria) this;
        }

        public Criteria andAppIdIsNotNull() {
            addCriterion("app_id is not null");
            return (Criteria) this;
        }

        public Criteria andAppIdEqualTo(String value) {
            addCriterion("app_id =", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotEqualTo(String value) {
            addCriterion("app_id <>", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdGreaterThan(String value) {
            addCriterion("app_id >", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdGreaterThanOrEqualTo(String value) {
            addCriterion("app_id >=", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdLessThan(String value) {
            addCriterion("app_id <", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdLessThanOrEqualTo(String value) {
            addCriterion("app_id <=", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdLike(String value) {
            addCriterion("app_id like", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotLike(String value) {
            addCriterion("app_id not like", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdIn(List<String> values) {
            addCriterion("app_id in", values, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotIn(List<String> values) {
            addCriterion("app_id not in", values, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdBetween(String value1, String value2) {
            addCriterion("app_id between", value1, value2, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotBetween(String value1, String value2) {
            addCriterion("app_id not between", value1, value2, "appId");
            return (Criteria) this;
        }

        public Criteria andAppSecretIsNull() {
            addCriterion("app_secret is null");
            return (Criteria) this;
        }

        public Criteria andAppSecretIsNotNull() {
            addCriterion("app_secret is not null");
            return (Criteria) this;
        }

        public Criteria andAppSecretEqualTo(String value) {
            addCriterion("app_secret =", value, "appSecret");
            return (Criteria) this;
        }

        public Criteria andAppSecretNotEqualTo(String value) {
            addCriterion("app_secret <>", value, "appSecret");
            return (Criteria) this;
        }

        public Criteria andAppSecretGreaterThan(String value) {
            addCriterion("app_secret >", value, "appSecret");
            return (Criteria) this;
        }

        public Criteria andAppSecretGreaterThanOrEqualTo(String value) {
            addCriterion("app_secret >=", value, "appSecret");
            return (Criteria) this;
        }

        public Criteria andAppSecretLessThan(String value) {
            addCriterion("app_secret <", value, "appSecret");
            return (Criteria) this;
        }

        public Criteria andAppSecretLessThanOrEqualTo(String value) {
            addCriterion("app_secret <=", value, "appSecret");
            return (Criteria) this;
        }

        public Criteria andAppSecretLike(String value) {
            addCriterion("app_secret like", value, "appSecret");
            return (Criteria) this;
        }

        public Criteria andAppSecretNotLike(String value) {
            addCriterion("app_secret not like", value, "appSecret");
            return (Criteria) this;
        }

        public Criteria andAppSecretIn(List<String> values) {
            addCriterion("app_secret in", values, "appSecret");
            return (Criteria) this;
        }

        public Criteria andAppSecretNotIn(List<String> values) {
            addCriterion("app_secret not in", values, "appSecret");
            return (Criteria) this;
        }

        public Criteria andAppSecretBetween(String value1, String value2) {
            addCriterion("app_secret between", value1, value2, "appSecret");
            return (Criteria) this;
        }

        public Criteria andAppSecretNotBetween(String value1, String value2) {
            addCriterion("app_secret not between", value1, value2, "appSecret");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeIsNull() {
            addCriterion("authorization_code is null");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeIsNotNull() {
            addCriterion("authorization_code is not null");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeEqualTo(String value) {
            addCriterion("authorization_code =", value, "authorizationCode");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeNotEqualTo(String value) {
            addCriterion("authorization_code <>", value, "authorizationCode");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeGreaterThan(String value) {
            addCriterion("authorization_code >", value, "authorizationCode");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeGreaterThanOrEqualTo(String value) {
            addCriterion("authorization_code >=", value, "authorizationCode");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeLessThan(String value) {
            addCriterion("authorization_code <", value, "authorizationCode");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeLessThanOrEqualTo(String value) {
            addCriterion("authorization_code <=", value, "authorizationCode");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeLike(String value) {
            addCriterion("authorization_code like", value, "authorizationCode");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeNotLike(String value) {
            addCriterion("authorization_code not like", value, "authorizationCode");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeIn(List<String> values) {
            addCriterion("authorization_code in", values, "authorizationCode");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeNotIn(List<String> values) {
            addCriterion("authorization_code not in", values, "authorizationCode");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeBetween(String value1, String value2) {
            addCriterion("authorization_code between", value1, value2, "authorizationCode");
            return (Criteria) this;
        }

        public Criteria andAuthorizationCodeNotBetween(String value1, String value2) {
            addCriterion("authorization_code not between", value1, value2, "authorizationCode");
            return (Criteria) this;
        }

        public Criteria andCodeExpireTimeIsNull() {
            addCriterion("code_expire_time is null");
            return (Criteria) this;
        }

        public Criteria andCodeExpireTimeIsNotNull() {
            addCriterion("code_expire_time is not null");
            return (Criteria) this;
        }

        public Criteria andCodeExpireTimeEqualTo(Date value) {
            addCriterion("code_expire_time =", value, "codeExpireTime");
            return (Criteria) this;
        }

        public Criteria andCodeExpireTimeNotEqualTo(Date value) {
            addCriterion("code_expire_time <>", value, "codeExpireTime");
            return (Criteria) this;
        }

        public Criteria andCodeExpireTimeGreaterThan(Date value) {
            addCriterion("code_expire_time >", value, "codeExpireTime");
            return (Criteria) this;
        }

        public Criteria andCodeExpireTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("code_expire_time >=", value, "codeExpireTime");
            return (Criteria) this;
        }

        public Criteria andCodeExpireTimeLessThan(Date value) {
            addCriterion("code_expire_time <", value, "codeExpireTime");
            return (Criteria) this;
        }

        public Criteria andCodeExpireTimeLessThanOrEqualTo(Date value) {
            addCriterion("code_expire_time <=", value, "codeExpireTime");
            return (Criteria) this;
        }

        public Criteria andCodeExpireTimeIn(List<Date> values) {
            addCriterion("code_expire_time in", values, "codeExpireTime");
            return (Criteria) this;
        }

        public Criteria andCodeExpireTimeNotIn(List<Date> values) {
            addCriterion("code_expire_time not in", values, "codeExpireTime");
            return (Criteria) this;
        }

        public Criteria andCodeExpireTimeBetween(Date value1, Date value2) {
            addCriterion("code_expire_time between", value1, value2, "codeExpireTime");
            return (Criteria) this;
        }

        public Criteria andCodeExpireTimeNotBetween(Date value1, Date value2) {
            addCriterion("code_expire_time not between", value1, value2, "codeExpireTime");
            return (Criteria) this;
        }

        public Criteria andAuthorizerRefreshTokenIsNull() {
            addCriterion("authorizer_refresh_token is null");
            return (Criteria) this;
        }

        public Criteria andAuthorizerRefreshTokenIsNotNull() {
            addCriterion("authorizer_refresh_token is not null");
            return (Criteria) this;
        }

        public Criteria andAuthorizerRefreshTokenEqualTo(String value) {
            addCriterion("authorizer_refresh_token =", value, "authorizerRefreshToken");
            return (Criteria) this;
        }

        public Criteria andAuthorizerRefreshTokenNotEqualTo(String value) {
            addCriterion("authorizer_refresh_token <>", value, "authorizerRefreshToken");
            return (Criteria) this;
        }

        public Criteria andAuthorizerRefreshTokenGreaterThan(String value) {
            addCriterion("authorizer_refresh_token >", value, "authorizerRefreshToken");
            return (Criteria) this;
        }

        public Criteria andAuthorizerRefreshTokenGreaterThanOrEqualTo(String value) {
            addCriterion("authorizer_refresh_token >=", value, "authorizerRefreshToken");
            return (Criteria) this;
        }

        public Criteria andAuthorizerRefreshTokenLessThan(String value) {
            addCriterion("authorizer_refresh_token <", value, "authorizerRefreshToken");
            return (Criteria) this;
        }

        public Criteria andAuthorizerRefreshTokenLessThanOrEqualTo(String value) {
            addCriterion("authorizer_refresh_token <=", value, "authorizerRefreshToken");
            return (Criteria) this;
        }

        public Criteria andAuthorizerRefreshTokenLike(String value) {
            addCriterion("authorizer_refresh_token like", value, "authorizerRefreshToken");
            return (Criteria) this;
        }

        public Criteria andAuthorizerRefreshTokenNotLike(String value) {
            addCriterion("authorizer_refresh_token not like", value, "authorizerRefreshToken");
            return (Criteria) this;
        }

        public Criteria andAuthorizerRefreshTokenIn(List<String> values) {
            addCriterion("authorizer_refresh_token in", values, "authorizerRefreshToken");
            return (Criteria) this;
        }

        public Criteria andAuthorizerRefreshTokenNotIn(List<String> values) {
            addCriterion("authorizer_refresh_token not in", values, "authorizerRefreshToken");
            return (Criteria) this;
        }

        public Criteria andAuthorizerRefreshTokenBetween(String value1, String value2) {
            addCriterion("authorizer_refresh_token between", value1, value2, "authorizerRefreshToken");
            return (Criteria) this;
        }

        public Criteria andAuthorizerRefreshTokenNotBetween(String value1, String value2) {
            addCriterion("authorizer_refresh_token not between", value1, value2, "authorizerRefreshToken");
            return (Criteria) this;
        }

        public Criteria andAuthorizerAccessTokenIsNull() {
            addCriterion("authorizer_access_token is null");
            return (Criteria) this;
        }

        public Criteria andAuthorizerAccessTokenIsNotNull() {
            addCriterion("authorizer_access_token is not null");
            return (Criteria) this;
        }

        public Criteria andAuthorizerAccessTokenEqualTo(String value) {
            addCriterion("authorizer_access_token =", value, "authorizerAccessToken");
            return (Criteria) this;
        }

        public Criteria andAuthorizerAccessTokenNotEqualTo(String value) {
            addCriterion("authorizer_access_token <>", value, "authorizerAccessToken");
            return (Criteria) this;
        }

        public Criteria andAuthorizerAccessTokenGreaterThan(String value) {
            addCriterion("authorizer_access_token >", value, "authorizerAccessToken");
            return (Criteria) this;
        }

        public Criteria andAuthorizerAccessTokenGreaterThanOrEqualTo(String value) {
            addCriterion("authorizer_access_token >=", value, "authorizerAccessToken");
            return (Criteria) this;
        }

        public Criteria andAuthorizerAccessTokenLessThan(String value) {
            addCriterion("authorizer_access_token <", value, "authorizerAccessToken");
            return (Criteria) this;
        }

        public Criteria andAuthorizerAccessTokenLessThanOrEqualTo(String value) {
            addCriterion("authorizer_access_token <=", value, "authorizerAccessToken");
            return (Criteria) this;
        }

        public Criteria andAuthorizerAccessTokenLike(String value) {
            addCriterion("authorizer_access_token like", value, "authorizerAccessToken");
            return (Criteria) this;
        }

        public Criteria andAuthorizerAccessTokenNotLike(String value) {
            addCriterion("authorizer_access_token not like", value, "authorizerAccessToken");
            return (Criteria) this;
        }

        public Criteria andAuthorizerAccessTokenIn(List<String> values) {
            addCriterion("authorizer_access_token in", values, "authorizerAccessToken");
            return (Criteria) this;
        }

        public Criteria andAuthorizerAccessTokenNotIn(List<String> values) {
            addCriterion("authorizer_access_token not in", values, "authorizerAccessToken");
            return (Criteria) this;
        }

        public Criteria andAuthorizerAccessTokenBetween(String value1, String value2) {
            addCriterion("authorizer_access_token between", value1, value2, "authorizerAccessToken");
            return (Criteria) this;
        }

        public Criteria andAuthorizerAccessTokenNotBetween(String value1, String value2) {
            addCriterion("authorizer_access_token not between", value1, value2, "authorizerAccessToken");
            return (Criteria) this;
        }

        public Criteria andTokenExpireTimeIsNull() {
            addCriterion("token_expire_time is null");
            return (Criteria) this;
        }

        public Criteria andTokenExpireTimeIsNotNull() {
            addCriterion("token_expire_time is not null");
            return (Criteria) this;
        }

        public Criteria andTokenExpireTimeEqualTo(Date value) {
            addCriterion("token_expire_time =", value, "tokenExpireTime");
            return (Criteria) this;
        }

        public Criteria andTokenExpireTimeNotEqualTo(Date value) {
            addCriterion("token_expire_time <>", value, "tokenExpireTime");
            return (Criteria) this;
        }

        public Criteria andTokenExpireTimeGreaterThan(Date value) {
            addCriterion("token_expire_time >", value, "tokenExpireTime");
            return (Criteria) this;
        }

        public Criteria andTokenExpireTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("token_expire_time >=", value, "tokenExpireTime");
            return (Criteria) this;
        }

        public Criteria andTokenExpireTimeLessThan(Date value) {
            addCriterion("token_expire_time <", value, "tokenExpireTime");
            return (Criteria) this;
        }

        public Criteria andTokenExpireTimeLessThanOrEqualTo(Date value) {
            addCriterion("token_expire_time <=", value, "tokenExpireTime");
            return (Criteria) this;
        }

        public Criteria andTokenExpireTimeIn(List<Date> values) {
            addCriterion("token_expire_time in", values, "tokenExpireTime");
            return (Criteria) this;
        }

        public Criteria andTokenExpireTimeNotIn(List<Date> values) {
            addCriterion("token_expire_time not in", values, "tokenExpireTime");
            return (Criteria) this;
        }

        public Criteria andTokenExpireTimeBetween(Date value1, Date value2) {
            addCriterion("token_expire_time between", value1, value2, "tokenExpireTime");
            return (Criteria) this;
        }

        public Criteria andTokenExpireTimeNotBetween(Date value1, Date value2) {
            addCriterion("token_expire_time not between", value1, value2, "tokenExpireTime");
            return (Criteria) this;
        }

        public Criteria andJsapiTicketIsNull() {
            addCriterion("jsapi_ticket is null");
            return (Criteria) this;
        }

        public Criteria andJsapiTicketIsNotNull() {
            addCriterion("jsapi_ticket is not null");
            return (Criteria) this;
        }

        public Criteria andJsapiTicketEqualTo(String value) {
            addCriterion("jsapi_ticket =", value, "jsapiTicket");
            return (Criteria) this;
        }

        public Criteria andJsapiTicketNotEqualTo(String value) {
            addCriterion("jsapi_ticket <>", value, "jsapiTicket");
            return (Criteria) this;
        }

        public Criteria andJsapiTicketGreaterThan(String value) {
            addCriterion("jsapi_ticket >", value, "jsapiTicket");
            return (Criteria) this;
        }

        public Criteria andJsapiTicketGreaterThanOrEqualTo(String value) {
            addCriterion("jsapi_ticket >=", value, "jsapiTicket");
            return (Criteria) this;
        }

        public Criteria andJsapiTicketLessThan(String value) {
            addCriterion("jsapi_ticket <", value, "jsapiTicket");
            return (Criteria) this;
        }

        public Criteria andJsapiTicketLessThanOrEqualTo(String value) {
            addCriterion("jsapi_ticket <=", value, "jsapiTicket");
            return (Criteria) this;
        }

        public Criteria andJsapiTicketLike(String value) {
            addCriterion("jsapi_ticket like", value, "jsapiTicket");
            return (Criteria) this;
        }

        public Criteria andJsapiTicketNotLike(String value) {
            addCriterion("jsapi_ticket not like", value, "jsapiTicket");
            return (Criteria) this;
        }

        public Criteria andJsapiTicketIn(List<String> values) {
            addCriterion("jsapi_ticket in", values, "jsapiTicket");
            return (Criteria) this;
        }

        public Criteria andJsapiTicketNotIn(List<String> values) {
            addCriterion("jsapi_ticket not in", values, "jsapiTicket");
            return (Criteria) this;
        }

        public Criteria andJsapiTicketBetween(String value1, String value2) {
            addCriterion("jsapi_ticket between", value1, value2, "jsapiTicket");
            return (Criteria) this;
        }

        public Criteria andJsapiTicketNotBetween(String value1, String value2) {
            addCriterion("jsapi_ticket not between", value1, value2, "jsapiTicket");
            return (Criteria) this;
        }

        public Criteria andTicketExpireTimeIsNull() {
            addCriterion("ticket_expire_time is null");
            return (Criteria) this;
        }

        public Criteria andTicketExpireTimeIsNotNull() {
            addCriterion("ticket_expire_time is not null");
            return (Criteria) this;
        }

        public Criteria andTicketExpireTimeEqualTo(Date value) {
            addCriterion("ticket_expire_time =", value, "ticketExpireTime");
            return (Criteria) this;
        }

        public Criteria andTicketExpireTimeNotEqualTo(Date value) {
            addCriterion("ticket_expire_time <>", value, "ticketExpireTime");
            return (Criteria) this;
        }

        public Criteria andTicketExpireTimeGreaterThan(Date value) {
            addCriterion("ticket_expire_time >", value, "ticketExpireTime");
            return (Criteria) this;
        }

        public Criteria andTicketExpireTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ticket_expire_time >=", value, "ticketExpireTime");
            return (Criteria) this;
        }

        public Criteria andTicketExpireTimeLessThan(Date value) {
            addCriterion("ticket_expire_time <", value, "ticketExpireTime");
            return (Criteria) this;
        }

        public Criteria andTicketExpireTimeLessThanOrEqualTo(Date value) {
            addCriterion("ticket_expire_time <=", value, "ticketExpireTime");
            return (Criteria) this;
        }

        public Criteria andTicketExpireTimeIn(List<Date> values) {
            addCriterion("ticket_expire_time in", values, "ticketExpireTime");
            return (Criteria) this;
        }

        public Criteria andTicketExpireTimeNotIn(List<Date> values) {
            addCriterion("ticket_expire_time not in", values, "ticketExpireTime");
            return (Criteria) this;
        }

        public Criteria andTicketExpireTimeBetween(Date value1, Date value2) {
            addCriterion("ticket_expire_time between", value1, value2, "ticketExpireTime");
            return (Criteria) this;
        }

        public Criteria andTicketExpireTimeNotBetween(Date value1, Date value2) {
            addCriterion("ticket_expire_time not between", value1, value2, "ticketExpireTime");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table weixin_gzh_authorizer
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table weixin_gzh_authorizer
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}