package weixin.assistant.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import weixin.assistant.model.VipBusiness;
import weixin.assistant.model.VipBusinessExample;

public interface VipBusinessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_business
     *
     * @mbggenerated
     */
    int countByExample(VipBusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_business
     *
     * @mbggenerated
     */
    int deleteByExample(VipBusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_business
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_business
     *
     * @mbggenerated
     */
    int insert(VipBusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_business
     *
     * @mbggenerated
     */
    int insertSelective(VipBusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_business
     *
     * @mbggenerated
     */
    List<VipBusiness> selectByExample(VipBusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_business
     *
     * @mbggenerated
     */
    VipBusiness selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_business
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") VipBusiness record, @Param("example") VipBusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_business
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") VipBusiness record, @Param("example") VipBusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_business
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(VipBusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_business
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(VipBusiness record);
}