package weixin.assistant.dao;

import java.util.List;
import java.util.Map;

public interface VipMemberExtendMapper{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_member
     *
     * @mbggenerated
     */
    int incMoneyInputByExample(Map<String, Integer> paras);
    int incMoneyOutputByExample(Map<String, Integer> paras);

    /**
     * 充值/消费 查询
     * @param czMap
     * @return
     */
    List<Map<String,Object>> czSearchForList(Map<String,Object> czMap);
    int czSearchTotalCount(Map<String,Object> czMap);

    List<Map<String,Object>> xfSearchForList(Map<String,Object> czMap);
    int xfSearchTotalCount(Map<String,Object> czMap);


    /**
     * 会员列表
     * @param czMap
     * @return
     */
    List<Map<String,Object>> vipQueryForList(Map<String,Object> czMap);
    int vipTotalCount(Map<String,Object> czMap);
    /**
     * 用户充值统计
     * @param czFinishTime
     * @return
     */
    List<Map<String,Object>> userRechargeStatics(Map<String,Object> czFinishTime);

    /**
     * 用户消费统计
     * @param czFinishTime
     * @return
     */
    List<Map<String,Object>> userPayStatics(Map<String,Object> czFinishTime);

    /**
     * 用户消费统计
     * @param czFinishTime
     * @return
     */
    List<Map<String,Object>> vipDataStatics(Map<String,Object> czFinishTime);

    /**
     * 商户信息查询
     * @param maps
     * @return
     */
    List<Map<String,Object>> businessList(Map<String,Object> maps);
    int businessTotalCount(Map<String,Object> maps);

    /**
     * 商户下 公账号信息
     * @param maps
     * @return
     */
    List<Map<String,Object>> gzhInfoList(Map<String,Object> maps);

}