package weixin.assistant.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import weixin.assistant.model.VipMessage;
import weixin.assistant.model.VipMessageExample;

public interface VipMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_message
     *
     * @mbggenerated
     */
    int countByExample(VipMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_message
     *
     * @mbggenerated
     */
    int deleteByExample(VipMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_message
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_message
     *
     * @mbggenerated
     */
    int insert(VipMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_message
     *
     * @mbggenerated
     */
    int insertSelective(VipMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_message
     *
     * @mbggenerated
     */
    List<VipMessage> selectByExample(VipMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_message
     *
     * @mbggenerated
     */
    VipMessage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_message
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") VipMessage record, @Param("example") VipMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_message
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") VipMessage record, @Param("example") VipMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_message
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(VipMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_message
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(VipMessage record);
}