package weixin.assistant.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import weixin.assistant.model.VipPayOrder;
import weixin.assistant.model.VipPayOrderExample;

public interface VipPayOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_pay_order
     *
     * @mbggenerated
     */
    int countByExample(VipPayOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_pay_order
     *
     * @mbggenerated
     */
    int deleteByExample(VipPayOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_pay_order
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_pay_order
     *
     * @mbggenerated
     */
    int insert(VipPayOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_pay_order
     *
     * @mbggenerated
     */
    int insertSelective(VipPayOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_pay_order
     *
     * @mbggenerated
     */
    List<VipPayOrder> selectByExample(VipPayOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_pay_order
     *
     * @mbggenerated
     */
    VipPayOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_pay_order
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") VipPayOrder record, @Param("example") VipPayOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_pay_order
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") VipPayOrder record, @Param("example") VipPayOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_pay_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(VipPayOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_pay_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(VipPayOrder record);
}