package weixin.assistant.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import weixin.assistant.model.VipRechargeOrder;
import weixin.assistant.model.VipRechargeOrderExample;

public interface VipRechargeOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_recharge_order
     *
     * @mbggenerated
     */
    int countByExample(VipRechargeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_recharge_order
     *
     * @mbggenerated
     */
    int deleteByExample(VipRechargeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_recharge_order
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_recharge_order
     *
     * @mbggenerated
     */
    int insert(VipRechargeOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_recharge_order
     *
     * @mbggenerated
     */
    int insertSelective(VipRechargeOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_recharge_order
     *
     * @mbggenerated
     */
    List<VipRechargeOrder> selectByExample(VipRechargeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_recharge_order
     *
     * @mbggenerated
     */
    VipRechargeOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_recharge_order
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") VipRechargeOrder record, @Param("example") VipRechargeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_recharge_order
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") VipRechargeOrder record, @Param("example") VipRechargeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_recharge_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(VipRechargeOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_recharge_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(VipRechargeOrder record);
}