package weixin.assistant.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import weixin.assistant.model.WeixinGzh;
import weixin.assistant.model.WeixinGzhExample;

public interface WeixinGzhMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_gzh
     *
     * @mbggenerated
     */
    int countByExample(WeixinGzhExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_gzh
     *
     * @mbggenerated
     */
    int deleteByExample(WeixinGzhExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_gzh
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_gzh
     *
     * @mbggenerated
     */
    int insert(WeixinGzh record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_gzh
     *
     * @mbggenerated
     */
    int insertSelective(WeixinGzh record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_gzh
     *
     * @mbggenerated
     */
    List<WeixinGzh> selectByExample(WeixinGzhExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_gzh
     *
     * @mbggenerated
     */
    WeixinGzh selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_gzh
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") WeixinGzh record, @Param("example") WeixinGzhExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_gzh
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") WeixinGzh record, @Param("example") WeixinGzhExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_gzh
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WeixinGzh record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_gzh
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WeixinGzh record);
}