package weixin.assistant.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import weixin.assistant.model.WeixinGzhAuthorizer;
import weixin.assistant.model.WeixinGzhAuthorizerExample;

public interface WeixinGzhAuthorizerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_gzh_authorizer
     *
     * @mbggenerated
     */
    int countByExample(WeixinGzhAuthorizerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_gzh_authorizer
     *
     * @mbggenerated
     */
    int deleteByExample(WeixinGzhAuthorizerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_gzh_authorizer
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_gzh_authorizer
     *
     * @mbggenerated
     */
    int insert(WeixinGzhAuthorizer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_gzh_authorizer
     *
     * @mbggenerated
     */
    int insertSelective(WeixinGzhAuthorizer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_gzh_authorizer
     *
     * @mbggenerated
     */
    List<WeixinGzhAuthorizer> selectByExample(WeixinGzhAuthorizerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_gzh_authorizer
     *
     * @mbggenerated
     */
    WeixinGzhAuthorizer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_gzh_authorizer
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") WeixinGzhAuthorizer record, @Param("example") WeixinGzhAuthorizerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_gzh_authorizer
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") WeixinGzhAuthorizer record, @Param("example") WeixinGzhAuthorizerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_gzh_authorizer
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WeixinGzhAuthorizer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_gzh_authorizer
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WeixinGzhAuthorizer record);
}