package weixin.assistant.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import weixin.assistant.model.WeixinGzhPay;
import weixin.assistant.model.WeixinGzhPayExample;

public interface WeixinGzhPayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_gzh_pay
     *
     * @mbggenerated
     */
    int countByExample(WeixinGzhPayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_gzh_pay
     *
     * @mbggenerated
     */
    int deleteByExample(WeixinGzhPayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_gzh_pay
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_gzh_pay
     *
     * @mbggenerated
     */
    int insert(WeixinGzhPay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_gzh_pay
     *
     * @mbggenerated
     */
    int insertSelective(WeixinGzhPay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_gzh_pay
     *
     * @mbggenerated
     */
    List<WeixinGzhPay> selectByExample(WeixinGzhPayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_gzh_pay
     *
     * @mbggenerated
     */
    WeixinGzhPay selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_gzh_pay
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") WeixinGzhPay record, @Param("example") WeixinGzhPayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_gzh_pay
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") WeixinGzhPay record, @Param("example") WeixinGzhPayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_gzh_pay
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WeixinGzhPay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_gzh_pay
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WeixinGzhPay record);
}