package weixin.assistant.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import weixin.assistant.model.WeixinUser;
import weixin.assistant.model.WeixinUserExample;

public interface WeixinUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_user
     *
     * @mbggenerated
     */
    int countByExample(WeixinUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_user
     *
     * @mbggenerated
     */
    int deleteByExample(WeixinUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_user
     *
     * @mbggenerated
     */
    int insert(WeixinUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_user
     *
     * @mbggenerated
     */
    int insertSelective(WeixinUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_user
     *
     * @mbggenerated
     */
    List<WeixinUser> selectByExample(WeixinUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_user
     *
     * @mbggenerated
     */
    WeixinUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_user
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") WeixinUser record, @Param("example") WeixinUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_user
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") WeixinUser record, @Param("example") WeixinUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WeixinUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WeixinUser record);
}